### PR TITLE
Fix Libs.private flags for mbedtls

### PR DESCRIPTION
**Pull request by joerg-krause**
Static linking with bctoolbox fails when using pkg-config as the
generated bctoolbox.pc file only consists of an '-L' string without any
search path or libraries flags.

That's because of an typo in `mbedtls_library_path`. However,
`mbedtls_library_path` contains a string of the mbedtls libraries
concatenated by an ';' which cannot be parsed by pkg-config.

Therefore, use `MBEDTLS_LIBRARY` instead of `MBEDTLS_LIBRARIES` to get
the library path.

Furthermore, add the three mbedtls libraries *mbedtls*, *mbedcrypto*, and
*mbedx509* to `LIBS_PRIVATE` so these libraries are added to the
`Libs.private` field of bctoolbox.pc.

### CODE REVIEW

**Comment by jehandelalune** [comment]
Thanks for reporting us this issue.
I fixed it slightly differently than your proposal.
Cheers

**Comment by joerg-krause** [comment]
I've tested this commit. The `Libs.private` is now:

```
Libs.private:  /mnt/data/git/buildroot/output/host/usr/arm-buildroot-linux-musleabi/sysroot/usr/lib32/libmbedtls.a /mnt/data/git/buildroot/output/host/usr/arm-buildroot-linux-musleabi/sysroot/usr/lib32/libmbedx509.a /mnt/data/git/buildroot/output/host/usr/arm-buildroot-linux-musleabi/sysroot/usr/lib32/libmbedcrypto.a
```

Which is not how the link flags for the libraries should be, but it should be this way:

```
Libs.private:  -L/mnt/data/git/buildroot/output/host/usr/arm-buildroot-linux-musleabi/sysroot/usr/lib32 -lmbedtls -lmbedx509 -lmbedcrypto
```

**Comment by joerg-krause** [comment]
@jehandelalune Friendly ping...

**Comment by jehandelalune** [comment]
Hi Joerg,

In the case you mentioned, private libraries are exported from mbedtls which is compiled statically. I'm not a pkg-config expert, but what is wrong in putting paths to static libs in a .pc file ?

**Comment by joerg-krause** [comment]
You do not pass the paths to the needed libraries, but the needed libraries as linker flags to `Libs.private`. Please have look at an [example .pc file](https://github.com/Distrotech/pkg-config/blob/dc910bd19d71bcf695ccaea943bb8eb38cb9df33/check/gtk/libpng.pc) from the pkg-config package.

Furthermore, having a look at how pkg-config [parses](https://github.com/Distrotech/pkg-config/blob/dc910bd19d71bcf695ccaea943bb8eb38cb9df33/parse.c#L721-L763) the `Libs.private` field, shows that it [looks for `-L` and `-l` chunks](https://github.com/Distrotech/pkg-config/blob/dc910bd19d71bcf695ccaea943bb8eb38cb9df33/parse.c#L603-L683) (without any suffix on Unix systems).

**Pull request closed without merging**
